//
//  FourCodePixelFormatReference.swift
//  PhosteraShared
//
//  Created by Gary Barnett on 11/4/23.
//

import Foundation
import AVFoundation

public class FourCodePixelFormatReference {
   public static var shared = FourCodePixelFormatReference()
    let list = [
        kCVPixelFormatType_1Monochrome,
        kCVPixelFormatType_2Indexed,
        kCVPixelFormatType_4Indexed,
        kCVPixelFormatType_8Indexed,
        kCVPixelFormatType_1IndexedGray_WhiteIsZero,
        kCVPixelFormatType_2IndexedGray_WhiteIsZero,
        kCVPixelFormatType_4IndexedGray_WhiteIsZero,
        kCVPixelFormatType_8IndexedGray_WhiteIsZero,
        kCVPixelFormatType_16BE555,
        kCVPixelFormatType_16LE555,
        kCVPixelFormatType_16LE5551,
        kCVPixelFormatType_16BE565,
        kCVPixelFormatType_16LE565,
        kCVPixelFormatType_24RGB,
        kCVPixelFormatType_24BGR,
        kCVPixelFormatType_32ARGB,
        kCVPixelFormatType_32BGRA,
        kCVPixelFormatType_32ABGR,
        kCVPixelFormatType_32RGBA,
        kCVPixelFormatType_64ARGB,
        kCVPixelFormatType_64RGBALE,
        kCVPixelFormatType_48RGB,
        kCVPixelFormatType_32AlphaGray,
        kCVPixelFormatType_16Gray,
        kCVPixelFormatType_30RGB,
        kCVPixelFormatType_422YpCbCr8,
        kCVPixelFormatType_4444YpCbCrA8,
        kCVPixelFormatType_4444YpCbCrA8R,
        kCVPixelFormatType_4444AYpCbCr8,
        kCVPixelFormatType_4444AYpCbCr16,
        kCVPixelFormatType_4444AYpCbCrFloat,
        kCVPixelFormatType_444YpCbCr8,
        kCVPixelFormatType_422YpCbCr16,
        kCVPixelFormatType_422YpCbCr10,
        kCVPixelFormatType_444YpCbCr10,
        kCVPixelFormatType_420YpCbCr8Planar,
        kCVPixelFormatType_420YpCbCr8PlanarFullRange,
        kCVPixelFormatType_422YpCbCr_4A_8BiPlanar,
        kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange,
        kCVPixelFormatType_420YpCbCr8BiPlanarFullRange,
        kCVPixelFormatType_422YpCbCr8BiPlanarVideoRange,
        kCVPixelFormatType_422YpCbCr8BiPlanarFullRange,
        kCVPixelFormatType_444YpCbCr8BiPlanarVideoRange,
        kCVPixelFormatType_444YpCbCr8BiPlanarFullRange,
        kCVPixelFormatType_422YpCbCr8_yuvs,
        kCVPixelFormatType_422YpCbCr8FullRange,
        kCVPixelFormatType_OneComponent8,
        kCVPixelFormatType_TwoComponent8,
        kCVPixelFormatType_30RGBLEPackedWideGamut,
        kCVPixelFormatType_ARGB2101010LEPacked,
        kCVPixelFormatType_40ARGBLEWideGamut,
        kCVPixelFormatType_40ARGBLEWideGamutPremultiplied,
        kCVPixelFormatType_OneComponent10,
        kCVPixelFormatType_OneComponent12,
        kCVPixelFormatType_OneComponent16,
        kCVPixelFormatType_TwoComponent16,
        kCVPixelFormatType_OneComponent16Half,
        kCVPixelFormatType_OneComponent32Float,
        kCVPixelFormatType_TwoComponent16Half,
        kCVPixelFormatType_TwoComponent32Float,
        kCVPixelFormatType_64RGBAHalf,
        kCVPixelFormatType_128RGBAFloat,
        kCVPixelFormatType_14Bayer_GRBG,
        kCVPixelFormatType_14Bayer_RGGB,
        kCVPixelFormatType_14Bayer_BGGR,
        kCVPixelFormatType_14Bayer_GBRG ,
        kCVPixelFormatType_DisparityFloat16,
        kCVPixelFormatType_DisparityFloat32,
        kCVPixelFormatType_DepthFloat16,
        kCVPixelFormatType_DepthFloat32,
        kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange,
        kCVPixelFormatType_422YpCbCr10BiPlanarVideoRange,
        kCVPixelFormatType_444YpCbCr10BiPlanarVideoRange,
        kCVPixelFormatType_420YpCbCr10BiPlanarFullRange,
        kCVPixelFormatType_422YpCbCr10BiPlanarFullRange,
        kCVPixelFormatType_444YpCbCr10BiPlanarFullRange,
        kCVPixelFormatType_420YpCbCr8VideoRange_8A_TriPlanar,
        kCVPixelFormatType_16VersatileBayer,
        kCVPixelFormatType_64RGBA_DownscaledProResRAW,
        kCVPixelFormatType_422YpCbCr16BiPlanarVideoRange,
        kCVPixelFormatType_444YpCbCr16BiPlanarVideoRange,
        kCVPixelFormatType_444YpCbCr16VideoRange_16A_TriPlanar,
        kCVPixelFormatType_Lossless_32BGRA,
        kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange,
        kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange,
        kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange,
        kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange,
        kCVPixelFormatType_Lossy_32BGRA,
        kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarVideoRange,
        kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarFullRange,
        kCVPixelFormatType_Lossy_420YpCbCr10PackedBiPlanarVideoRange,
        kCVPixelFormatType_Lossy_422YpCbCr10PackedBiPlanarVideoRange
    ]
    
    let listItemDesc = [
        "kCVPixelFormatType_1Monochrome",
        "kCVPixelFormatType_2Indexed",
        "kCVPixelFormatType_4Indexed",
        "kCVPixelFormatType_8Indexed",
        "kCVPixelFormatType_1IndexedGray_WhiteIsZero",
        "kCVPixelFormatType_2IndexedGray_WhiteIsZero",
        "kCVPixelFormatType_4IndexedGray_WhiteIsZero",
        "kCVPixelFormatType_8IndexedGray_WhiteIsZero",
        "kCVPixelFormatType_16BE555",
        "kCVPixelFormatType_16LE555",
        "kCVPixelFormatType_16LE5551",
        "kCVPixelFormatType_16BE565",
        "kCVPixelFormatType_16LE565",
        "kCVPixelFormatType_24RGB",
        "kCVPixelFormatType_24BGR",
        "kCVPixelFormatType_32ARGB",
        "kCVPixelFormatType_32BGRA",
        "kCVPixelFormatType_32ABGR",
        "kCVPixelFormatType_32RGBA",
        "kCVPixelFormatType_64ARGB",
        "kCVPixelFormatType_64RGBALE",
        "kCVPixelFormatType_48RGB",
        "kCVPixelFormatType_32AlphaGray",
        "kCVPixelFormatType_16Gray",
        "kCVPixelFormatType_30RGB",
        "kCVPixelFormatType_422YpCbCr8",
        "kCVPixelFormatType_4444YpCbCrA8",
        "kCVPixelFormatType_4444YpCbCrA8R",
        "kCVPixelFormatType_4444AYpCbCr8",
        "kCVPixelFormatType_4444AYpCbCr16",
        "kCVPixelFormatType_4444AYpCbCrFloat",
        "kCVPixelFormatType_444YpCbCr8",
        "kCVPixelFormatType_422YpCbCr16",
        "kCVPixelFormatType_422YpCbCr10",
        "kCVPixelFormatType_444YpCbCr10",
        "kCVPixelFormatType_420YpCbCr8Planar",
        "kCVPixelFormatType_420YpCbCr8PlanarFullRange",
        "kCVPixelFormatType_422YpCbCr_4A_8BiPlanar",
        "kCVPixelFormatType_420YpCbCr8BiPlanarVideoRange",
        "kCVPixelFormatType_420YpCbCr8BiPlanarFullRange",
        "kCVPixelFormatType_422YpCbCr8BiPlanarVideoRange",
        "kCVPixelFormatType_422YpCbCr8BiPlanarFullRange",
        "kCVPixelFormatType_444YpCbCr8BiPlanarVideoRange",
        "kCVPixelFormatType_444YpCbCr8BiPlanarFullRange",
        "kCVPixelFormatType_422YpCbCr8_yuvs",
        "kCVPixelFormatType_422YpCbCr8FullRange",
        "kCVPixelFormatType_OneComponent8",
        "kCVPixelFormatType_TwoComponent8",
        "kCVPixelFormatType_30RGBLEPackedWideGamut",
        "kCVPixelFormatType_ARGB2101010LEPacked",
        "kCVPixelFormatType_40ARGBLEWideGamut",
        "kCVPixelFormatType_40ARGBLEWideGamutPremultiplied",
        "kCVPixelFormatType_OneComponent10",
        "kCVPixelFormatType_OneComponent12",
        "kCVPixelFormatType_OneComponent16",
        "kCVPixelFormatType_TwoComponent16",
        "kCVPixelFormatType_OneComponent16Half",
        "kCVPixelFormatType_OneComponent32Float",
        "kCVPixelFormatType_TwoComponent16Half",
        "kCVPixelFormatType_TwoComponent32Float",
        "kCVPixelFormatType_64RGBAHalf",
        "kCVPixelFormatType_128RGBAFloat",
        "kCVPixelFormatType_14Bayer_GRBG",
        "kCVPixelFormatType_14Bayer_RGGB",
        "kCVPixelFormatType_14Bayer_BGGR",
        "kCVPixelFormatType_14Bayer_GBRG ",
        "kCVPixelFormatType_DisparityFloat16",
        "kCVPixelFormatType_DisparityFloat32",
        "kCVPixelFormatType_DepthFloat16",
        "kCVPixelFormatType_DepthFloat32",
        "kCVPixelFormatType_420YpCbCr10BiPlanarVideoRange",
        "kCVPixelFormatType_422YpCbCr10BiPlanarVideoRange",
        "kCVPixelFormatType_444YpCbCr10BiPlanarVideoRange",
        "kCVPixelFormatType_420YpCbCr10BiPlanarFullRange",
        "kCVPixelFormatType_422YpCbCr10BiPlanarFullRange",
        "kCVPixelFormatType_444YpCbCr10BiPlanarFullRange",
        "kCVPixelFormatType_420YpCbCr8VideoRange_8A_TriPlanar",
        "kCVPixelFormatType_16VersatileBayer",
        "kCVPixelFormatType_64RGBA_DownscaledProResRAW",
        "kCVPixelFormatType_422YpCbCr16BiPlanarVideoRange",
        "kCVPixelFormatType_444YpCbCr16BiPlanarVideoRange",
        "kCVPixelFormatType_444YpCbCr16VideoRange_16A_TriPlanar",
        "kCVPixelFormatType_Lossless_32BGRA",
        "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarVideoRange",
        "kCVPixelFormatType_Lossless_420YpCbCr8BiPlanarFullRange",
        "kCVPixelFormatType_Lossless_420YpCbCr10PackedBiPlanarVideoRange",
        "kCVPixelFormatType_Lossless_422YpCbCr10PackedBiPlanarVideoRange",
        "kCVPixelFormatType_Lossy_32BGRA",
        "kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarVideoRange",
        "kCVPixelFormatType_Lossy_420YpCbCr8BiPlanarFullRange",
        "kCVPixelFormatType_Lossy_420YpCbCr10PackedBiPlanarVideoRange",
        "kCVPixelFormatType_Lossy_422YpCbCr10PackedBiPlanarVideoRange"
    ]
    
  public func display() {
        for (index, fourCC) in list.enumerated() {
            var str = ""
            for i in 0..<4 {
                let byte = UInt8((fourCC >> (i * 8)) & 0xFF)
                str = String(UnicodeScalar(byte)) + str
            }
            print("\(str) - \(listItemDesc[index])")
        }
    }
    
}
